version: "3"




services:

  rotas:

    image: henriqu33bbr/projeto:1.4.7

    container_name: rotas

    ports:

      - "8000:8000"

    networks:

      - social-network

    depends_on:
      - auth

  auth:

    image: henriqu33bbr/auth:1.3.1
    

    container_name: auth

    ports:

      - "9999:9999"
    networks:

      - social-network

  batalha:

    image: viniciustech/batalha

    container_name: batalha

    ports:

      - "6001:6001"

    networks:

      - social-network

  juan:

    image: juan110588/kafka-poke:0.1.3

    container_name: juan

    ports:

      - "8484:8484"

    networks:

      - social-network



  zookeeper:

    image: wurstmeister/zookeeper

    container_name: zookeeper

    ports:

      - "2181:2181"

    networks:

      - social-network

  kafka:

    image: wurstmeister/kafka

    container_name: kafka

    ports:

      - "9092:9092"

    environment:

      KAFKA_ADVERTISED_HOST_NAME: localhost

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    depends_on:

      - zookeeper

    networks:

      - social-network

  redis:

    hostname: redis

    container_name: redis

    restart: unless-stopped

    image: redis:alpine

    ports:

      - "6379:6379"

    command: redis-server /etc/redis/redis.conf

    volumes:

      - /etc/redis/redis.conf:/etc/redis/redis.conf

      - /etc/redis/users.acl:/etc/redis/users.acl

    environment:

      - REDIS_USER="user"

      - REDIS_PASSWORD="1234"

    networks:

      - social-network



networks:

  social-network:

    name: social-network